### ISSUE TITLE
unable to add from jcenter in android studio 1.3.2

### ISSUE THREAD

**Issue by ksy5662** [wasabeef/picasso-transformations#10]
Couldn't get this library from jcenter

Anything I missed here?

![image](https://cloud.githubusercontent.com/assets/1783034/9950722/7a19ac50-5df8-11e5-860b-8d66db650cef.png)

buildscript {
    repositories {

        mavenCentral()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
    }
}

repositories {
    mavenCentral()

    // for using SNAPSHOT
    //maven {
    //    url uri('https://oss.sonatype.org/content/repositories/snapshots/')
    //}
}

apply plugin: 'com.android.application'

dependencies {
    compile project(':library')
    // Or, fetch from Maven:
    // compile 'com.google.maps.android:android-maps-utils:0.3+'
    compile 'com.android.support:support-v4:22.2.0'
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.google.android.gms:play-services:7.8.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'org.jsoup:jsoup:1.8.2'
    compile 'jp.wasabeef:picasso-transformations:1.2.0'
    // If you want to use the GPU Filters
    //compile 'jp.co.cyberagent.android.gpuimage:gpuimage-library:1.3.0'
    compile project(':appiraterAndroid')
}

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "com.teamhj.agriweather"
        minSdkVersion 16
        targetSdkVersion 21
        versionCode 1010
        versionName "1.0.10"
        renderscriptTargetApi 22
        renderscriptSupportModeEnabled true
    }
    buildTypes {

        debug {
            debuggable true
        }

        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            res.srcDirs = ['res']
        }
    }

    signingConfigs {
        debug {
            storeFile file('debug.keystore')
        }
    }
}

task startDemo(type: Exec) {
    dependsOn 'installDebug'
    def adb = new File("${System.env.ANDROID_HOME}", "platform-tools${File.separator}adb")
    commandLine adb, "shell", "am", "start", "-n", "com.google.maps.android.utils.demo/.MainActivity"
}

**Comment by wasabeef** [comment]
@ksy5662

try it.
```
buildscript {
  repositories {
    mavenCentral()
    jcenter()                         /*** this one ***/
  }

  dependencies {
    classpath 'com.android.tools.build:gradle:1.3.0'
  }
}
```
or
```
repositories {
  mavenCentral()
  jcenter()                            /*** this one ***/
  // for using SNAPSHOT
  //maven {
  //    url uri('https://oss.sonatype.org/content/repositories/snapshots/')
  //}
}
```

**Comment by ksy5662** [comment]
repositories outside of build script works!!

Thanks a lot for your great work!!

**Comment by wasabeef** [comment]
:shipit:
