### ISSUE TITLE
Crop Left

### ISSUE THREAD

**Issue by cshalysongoncalves** [wasabeef/picasso-transformations#14]
Hello,

I need doing crop the image left! Have any suggestions or solution?

**Comment by molexx** [comment]
I've been working on enhanced cropping which is now available for testing from my fork, a library build is here:

https://github.com/molexx/picasso-transformations/releases/tag/2.0.0-enhancedCrop

Javadoc for the various constructors has been added, there should be something to do what you want as you can now specify separate horizontal and vertical gravity:

https://github.com/molexx/picasso-transformations/blob/master/transformations/src/main/java/jp/wasabeef/picasso/transformations/CropTransformation.java

Feedback would be great please.

**Comment by wasabeef** [comment]
@molexx 

hi.

Please PR :+1:

**Comment by wasabeef** [comment]
@cshalysongoncalves @molexx 

Try `2.1.0`

**Comment by cshalysongoncalves** [comment]
@wasabeef thakns!
