### ISSUE TITLE
Build failed with duplicate libraries

### ISSUE THREAD

**Issue by Ethan-Velosys** [wasabeef/picasso-transformations#15]
Couldn't build my project with your library included. 

Error:duplicate files during packaging of APK <local app path>/app/build/outputs/apk/app-debug-unaligned.apk
	Path in archive: lib/armeabi-v7a/libblasV8.so
	Origin 1: <local app path>/app/build/intermediates/exploded-aar/jp.wasabeef/picasso-transformations/1.3.1/jni/armeabi-v7a/libblasV8.so
	Origin 2: <android sdk>/build-tools/23.0.2/renderscript/lib/packaged/armeabi-v7a/libblasV8.so
You can ignore those files in your build.gradle:
	android {
	  packagingOptions {
	    exclude 'lib/armeabi-v7a/libblasV8.so'
	  }
	}
Error:Execution failed for task ':app:packageDebug'.
> Duplicate files copied in APK lib/armeabi-v7a/libblasV8.so
  	File 1: <local app path>/app/build/intermediates/exploded-aar/jp.wasabeef/picasso-transformations/1.3.1/jni/armeabi-v7a/libblasV8.so
  	File 2: <android sdk>/build-tools/23.0.2/renderscript/lib/packaged/armeabi-v7a/libblasV8.so

I tried excluding the lib from packaging options as suggested by the compiler, but it didn't work. That could be a problem on my end. I'll be going with another library in any case. I also tried

**Comment by wasabeef** [comment]
@Ethan-Velosys 


try `2.1.0`

We removed the v8RenderScript.
