### ISSUE TITLE
Crop not working as expected?

### ISSUE THREAD

**Issue by molexx** [wasabeef/picasso-transformations#17]
CropCenter isn't doing what I expect in the example app. The demo.jpg is 640x359 and the CropCenter example crops it to 300x100 center - I would expect the resulting image to just about cover the dogs' heads but it seems to be full width as you can see the red stripe on the far left of the first dog and the wicker basket on the shelf on the right?

What I expect it to look like:
![demo_center_crop_300_100](https://cloud.githubusercontent.com/assets/210764/13902548/6f346cda-ee44-11e5-84b2-e69b9b936e33.jpg)

Screenshot from demo app:
![image](https://cloud.githubusercontent.com/assets/210764/13902574/5a102974-ee45-11e5-89a0-8199f58b467c.png)

**Comment by molexx** [comment]
I've had a go at fixing this along with adding cropping to an aspect ratio and cropping with a size relative to the original image, with limited testing it seems OK. I've added several new use cases to the bottom of the example app.

https://github.com/molexx/picasso-transformations

I've built an .aar for testing:
https://github.com/molexx/picasso-transformations/releases/tag/2.0.0-enhancedCrop

If I've misunderstood the intention of the existing crop then this will break it completely. Please feedback and I'll send a PR if all is good.

**Comment by wasabeef** [comment]
@molexx 

I was release. 2.1.0
