### ISSUE TITLE
CropCircleTransformation creates an extra Bitmap

### ISSUE THREAD

**Issue by pushbit** [wasabeef/picasso-transformations#2]
I believe it's not necessary to create `squaredBitmap`.  Instead, the `BitmapShader` can be given a `Matrix` that has `setTranslate(-width, -height)`.  This should accomplish the same thing that creating `squaredBitmap` does, shifting the viewport on `source` so that its centre is drawn into `bitmap`.

**Comment by wasabeef** [comment]
Hi.

Let's follow up on that issue.

**Comment by pushbit** [comment]
Created pull request #3 to resolve this.
