### ISSUE TITLE
Cannot compile with proguard

### ISSUE THREAD

**Issue by nrodriguez-tupaca** [wasabeef/picasso-transformations#39]
Since #36  It throws an error compiling:

> Warning:Exception while processing task java.io.IOException: proguard.ParseException: Unknown option 'com.squareup.okhttp' in line 3 of file '/Users/user/.gradle/caches/transforms-1/files-1.1/picasso-transformations-2.2.0.aar/16c5d97f0c603c4db20540986cd71722/proguard.txt'

In [picasso-transformations/transformations/proguard-rules.txt](https://github.com/wasabeef/picasso-transformations/blob/master/transformations/proguard-rules.txt) it says:
`-dontwarn dontwarn com.squareup.okhttp`
I think it should be:
`-dontwarn com.squareup.okhttp`

**Comment by wasabeef** [comment]
@nrodriguez-tupaca 

Thanks.

https://github.com/wasabeef/picasso-transformations/pull/37

**Comment by wasabeef** [comment]
I just released the new version to `2.2.1`.
